name: psit_lite_demo
description: "A lightweight minimal alternative to original PSIT App."
publish_to: 'none'
version: 1.0.6+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  encrypt: ^5.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  image: ^4.5.4
  google_fonts: ^6.2.1
  envied: ^1.1.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.5.4
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon_light.png
    - assets/icon_dark.png
    - assets/mock/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon_foreground.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"
  adaptive_icon_background: "#ffffff"